name: "airbnb_private"
type: "python:3.10"

relationships:
    database: "db:postgresql"

web:
    upstream:
        socket_family: unix
    commands:
        start: pipenv run gunicorn -w 4 -b unix:/tmp/airbnb_private.sock airbnb_private.wsgi:application

    locations:
        "/":
            passthru: true
        "/static":
            root: "static"
            expires: 1h
            allow: true

disk: 512

mounts:
    "logs":
        source: local
        source_path: logs

hooks:
    build: |
        pip install pipenv  # Install pipenv
        pipenv install --deploy  # Install dependencies from Pipfile
        

        mkdir logs
        pipenv run python manage.py collectstatic
        rm -rf logs
    deploy: |
        pipenv run python manage.py migrate

