name: "airbnb_project"
type: "python:3.10"

relationships:
    database: "db:postgresql"

# The configuration of the app when it's exposed to the web.
web:
    upstream:
        socket_family: unix
    commands:
        start: uwsgi --http-socket /run/app.sock --wsgi-file airbnb_project/wsgi.py --master --processes 4 --threads 2

    locations:
        "/":
            passthru: true
        "/static":
            root: "static"
            expires: 1h
            allow: true

# The size of the persistent disk of the application (in MB).
disk: 512

# Set a local read/write mount for logs.
mounts:
    "logs":
        source: local
        source_path: logs

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
        pip install pipenv  # Install pipenv
        pipenv install --deploy  # Install dependencies from Pipfile
        
        mkdir logs
        pipenv run python manage.py collectstatic
        rm -rf logs
    deploy: |
        pipenv run python manage.py migrate
