# Generated by Django 5.0 on 2024-02-11 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airbnb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('rooms', models.PositiveSmallIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('avalability', models.BooleanField(default=True)),
                ('services', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OtherService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Airbnbimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpeg', upload_to='images/')),
                ('airbnb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='airbnb.airbnb')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('airbnb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb.airbnb')),
            ],
        ),
        migrations.CreateModel(
            name='OtherServices',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('service_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='airbnb.otherservice')),
            ],
        ),
    ]
