# Generated by Django 5.0.2 on 2024-02-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpeg', upload_to='images/')),
                ('purpose', models.CharField(choices=[('airbnb', 'Airbnb Image'), ('mover', 'Mover Image')], default='airbnb', max_length=20)),
            ],
        ),
    ]
