# Generated by Django 5.0 on 2024-02-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherServices',
            new_name='OtherServicesBooking',
        ),
    ]
