# Generated by Django 5.0 on 2024-02-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0002_rename_otherservices_otherservicesbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbnb',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
