# Generated by Django 5.0 on 2024-01-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0013_alter_customer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherServices',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('avalability', models.BooleanField(default=True)),
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
