# Generated by Django 5.0.2 on 2024-02-12 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('available_areas', models.TextField(default='kisumu')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('relocate_from', models.CharField(max_length=50)),
                ('relocate_to', models.CharField(max_length=50)),
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movers.service')),
            ],
        ),
    ]
