# Generated by Django 5.0.2 on 2024-03-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='relocate_from',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='relocate_to',
        ),
    ]
