# Generated by Django 5.0 on 2023-12-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movers', '0006_alter_customer_booking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
