# Generated by Django 5.0 on 2024-02-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movers', '0007_otherservices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherServices',
        ),
    ]
